=== TeamKun/Scenamatica/action.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Scenamatica Action",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the action"
    },
    "description": {
      "type": "string",
      "description": "A description of the action"
    },
    "base": {
      "type": "string",
      "description": "The base action to use for the action"
    },
    "executable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is executed"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is executable"
        }
      ]
    },
    "watchable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is watched"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is watchable"
        }
      ]
    },
    "requireable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is required"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is requireable"
        }
      ]
    },
    "events": {
      "type": "array",
      "description": "The events that the action can emit",
      "items": {
        "type": "string"
      }
    },
    "arguments": {
      "type": "object",
      "description": "The arguments for the action",
      "additionalProperties": true,
      "patternProperties": {
        "^[a-zA-Z0-9_]+$": {
          "type": "object",
          "properties": {
            "requiredOn": {
              "oneOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "array",
                  "items": [
                    {
                      "type": "string",
                      "enum": [
                        "execute",
                        "watch",
                        "require"
                      ]
                    }
                  ]
                }
              ]
            },
            "availableFor": {
              "type": "array",
              "items": [
                {
                  "type": "string",
                  "enum": [
                    "execute",
                    "watch",
                    "require"
                  ]
                }
              ]
            }
          },
          "additionalProperties": true
        }
      }
    },
    "outputs": {
      "type": "object",
      "description": "The output of the action",
      "additionalProperties": true,
      "patternProperties": {
        "^[a-zA-Z0-9_]+$": {
          "type": "object",
          "properties": {
            "availableFor": {
              "type": "array",
              "items": [
                {
                  "type": "string",
                  "enum": [
                    "execute",
                    "watch",
                    "require"
                  ]
                }
              ]
            }
          },
          "additionalProperties": true
        }
      }
    }
  },
  "required": [
    "name",
    "description",
    "executable",
    "watchable",
    "requireable"
  ],
  "additionalProperties": false
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/entity/spawn.json
{
  "name": "entity_spawn",
  "description": "エンティティをスポーンさせます。",
  "events": [
    "org.bukkit.event.entity.EntitySpawnEvent"
  ],

  "executable": "エンティティをスポーンさせます。",
  "watchable": "エンティティがスポーンすることを期待します。",
  "requireable": false,

  "arguments": {
    "entity": {
      "type": "entity",
      "requiredOn": ["execute"]
    }
  },
  "outputs": {
    "entity": {
      "type": "entity"
    }
  }
}

=== TeamKun/Scenamatica/src/schema/schema/actions/player/sprint.json
{
  "name": "player_sprint",
  "description": "プレイヤを走らせます。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerToggleSprintEvent"
  ],

  "executable": "プレイヤの走り状態を変更します。",
  "watchable": "プレイヤが走るか期待します。",
  "requireable": "プレイヤが走っていることを要求します。",

  "arguments": {
    "sprinting": {
      "type": "boolean",
      "description": "プレイヤが走っているかどうかです。"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/block/place.json
{
  "name": "block_place",
  "description": "ブロックの設置を期待します。",
  "base": "block_$base",
  "events": [
    "org.bukkit.event.block.BlockPlaceEvent"
  ],

  "executable": "指定されたブロックを設置します。",
  "watchable": "指定されたブロックの設置を期待します。",
  "requireable": "指定されたブロックが空気ではないかどうかを判定します。",

  "arguments": {
    "actor": {
      "type": "playerSpecifier",
      "description": "ブロックを破壊したアクタです。",
      "availableFor": ["execute", "watch"]
    },
    "hand": {
      "type": "string",
      "description": "ブロックを設置した手です。",
      "enum": [
        "HAND",
        "OFF_HAND"
      ],
      "availableFor": ["execute"]
    },
    "direction": {
      "description": "ブロックを設置する方向です。",
      "type": "blockFace",
      "availableFor": ["execute"]
    }
  },

  "outputs": {
    "player": {
      "type": "player",
      "description": "ブロックを設置したプレイヤです。"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/bucket-entity.json
{
  "name": "player_bucket_entity",
  "description": "プレイヤがバケツにエンティティを入れます。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerBucketEntityEvent"
  ],

  "executable": "プレイヤにエンティティをバケツに入れさせます。",
  "watchable": "プレイヤがエンティティをバケツに入れるか期待します。",
  "requireable": false,

  "arguments": {
    "bucket": {
      "type": "itemStack",
      "description": "エンティティをいれるバケツです。"
    },
    "entityBucket": {
      "type": "itemStack",
      "description": "エンティティが入ったバケツです。"
    },
    "entity": {
      "type": "entitySpecifier",
      "description": "入れるエンティティです。",
      "requiredOn": ["execute"]
    }
  },
  "outputs": {
    "bucket": {
      "description": "エンティティをいれたバケツです。",
      "type": "itemStack"
    },
    "entityBucket": {
      "description": "エンティティが入ったバケツです。",
      "type": "itemStack"
    },
    "entity": {
      "description": "入れたエンティティです。",
      "type": "entity"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/scenamatica/negate.json
{
  "name": "negate",
  "description": "条件要求アクションの判定結果を反転します。",
  "executable": false,
  "watchable": false,
  "requireable": "条件要求アクションの判定結果を反転して取得します。",
  "arguments": {
    "action": {
      "type": "actionKinds",
      "$scenarioKindOf": "require",
      "requiredOn": true
    },
    "with": {
      "type": "actionArgument",
      "description": "アクションの種類によっては、このプロパティにアクションの引数を指定します。"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/kick.json
{
  "name": "player_kick",
  "description": "プレイヤをサーバから強制退出させます。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerKickEvent"
  ],

  "executable": "プレイヤをサーバから強制退出させます。",
  "watchable": "プレイヤがサーバから強制退出させらるか期待します。",
  "requireable": false,

  "arguments": {
    "leaveMessage": {
      "type": "string",
      "description": "プレイヤがサーバーから退出したときに表示するメッセージです。",
      "availableFor": ["watch"]
    },
    "message": {
      "type": "string",
      "description": "プレイヤがサーバーからキックされたときに表示するメッセージです。",
      "since": "1.16.5"
    }
  },
  "outputs": {
    "leaveMessage": {
      "type": "string",
      "description": "プレイヤがサーバーから退出したときに表示するメッセージです。",
      "availableFor": ["watch"]
    },
    "message": {
      "type": "string",
      "description": "プレイヤがサーバーからキックされたときに表示するメッセージです。",
      "since": "1.16.5"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/server/plugin-disable.json
{
  "name": "server_plugin_disable",
  "description": "サーバのプラグインを無効化します。",
  "events": [
    "org.bukkit.event.server.PluginDisableEvent"
  ],

  "executable": "サーバのプラグインを無効化します。",
  "watchable": "サーバのプラグインが無効化されるか期待します。",
  "requireable": "プラグインが無効であることを要求します。",

  "arguments": {
    "plugin": {
      "type": "string",
      "description": "無効化されるプラグインです。",
      "requiredOn": ["execute", "require"]
    }
  },
  "outputs": {
    "plugin": {
      "type": "string",
      "description": "無効化されたプラグインです。"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/interact-at-entity.json
{
  "name": "player_interact_at_entity",
  "description": "プレイヤにエンティティをクリックさせます。",
  "base": "player_interact_entity",
  "events": [
    "org.bukkit.event.player.PlayerInteractAtEntityEvent"
  ],

  "executable": "プレイヤにエンティティをクリックさせます。",
  "watchable": "プレイヤがエンティティをクリックすることを期待します。",
  "requireable": false,

  "arguments": {
    "position": {
      "type": "location",
      "description": "クリックするエンティティの場所です。",
      "requiredOn": ["execute"]
    }
  },
  "outputs": {
    "position": {
      "description": "クリックしたエンティティの場所です。",
      "type": "location"
    }
  }
}
