=== TeamKun/Scenamatica/action.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Scenamatica Action",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the action"
    },
    "description": {
      "type": "string",
      "description": "A description of the action"
    },
    "base": {
      "type": "string",
      "description": "The base action to use for the action"
    },
    "executable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is executed"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is executable"
        }
      ]
    },
    "watchable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is watched"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is watchable"
        }
      ]
    },
    "requireable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is required"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is requireable"
        }
      ]
    },
    "events": {
      "type": "array",
      "description": "The events that the action can emit",
      "items": {
        "type": "string"
      }
    },
    "arguments": {
      "type": "object",
      "description": "The arguments for the action",
      "additionalProperties": true,
      "patternProperties": {
        "^[a-zA-Z0-9_]+$": {
          "type": "object",
          "properties": {
            "requiredOn": {
              "oneOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "array",
                  "items": [
                    {
                      "type": "string",
                      "enum": [
                        "execute",
                        "watch",
                        "require"
                      ]
                    }
                  ]
                }
              ]
            },
            "availableFor": {
              "type": "array",
              "items": [
                {
                  "type": "string",
                  "enum": [
                    "execute",
                    "watch",
                    "require"
                  ]
                }
              ]
            }
          },
          "additionalProperties": true
        }
      }
    },
    "outputs": {
      "type": "object",
      "description": "The output of the action",
      "additionalProperties": true,
      "patternProperties": {
        "^[a-zA-Z0-9_]+$": {
          "type": "object",
          "properties": {
            "availableFor": {
              "type": "array",
              "items": [
                {
                  "type": "string",
                  "enum": [
                    "execute",
                    "watch",
                    "require"
                  ]
                }
              ]
            }
          },
          "additionalProperties": true
        }
      }
    }
  },
  "required": [
    "name",
    "description",
    "executable",
    "watchable",
    "requireable"
  ],
  "additionalProperties": false
}

=== TeamKun/Scenamatica/docs/schema/actions/entity/damage-by-entity.json
{
  "name": "entity_damage_by_entity",
  "description": "エンティティによるダメージをエンティティに与えます。",
  "base": "entity_damage",
  "events": [
    "org.bukkit.event.entity.EntityDamageByEntityEvent"
  ],

  "executable": "エンティティによるダメージをエンティティに与えます。",
  "watchable": "エンティティがエンティティによるダメージを受けることを期待します。",
  "requireable": false,

  "arguments": {
    "damager": {
      "type": "entitySpecifier",
      "description": "ダメージ元のエンティティです。",
      "requiredOn": ["execute"]
    },
    "cause": {
      "requiredOn": false
    }
  },
  "outputs": {
    "damager": {
      "description": "ダメージ元となったエンティティです。",
      "type": "entity"
    }
  }
}

=== TeamKun/Scenamatica/src/schema/schema/actions/server/tab-complete.json
{
  "name": "tab_complete",
  "description": "コマンドをタブ補完します。",
  "events": [
    "org.bukkit.event.server.TabCompleteEvent"
  ],

  "executable": "コマンドをタブ補完します。",
  "watchable": "コマンドがタブ補完されることを期待します。",
  "requireable": false,

  "arguments": {
    "sender": {
      "description": "実行するプレイヤです。",
      "oneOf": [
        {
          "type": "playerSpecifier"
        },
        {
          "type": "string",
          "const": "<CONSOLE>",
          "description": "コンソールを表します。"
        }
      ]
    },
    "buffer": {
      "type": "string",
      "description": "入力された不完全なコマンドです。補完を期待する場合は正規表現を使用できます。",
      "requiredOn": ["execute"]
    },
    "completions": {
      "type": "array",
      "description": "補完候補の配列です。補完を期待する場合は正規表現を使用できます。"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/join.json
{
  "name": "player_join",
  "description": "プレイヤをサーバに参加させます。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerJoinEvent"
  ],

  "executable": "プレイヤをサーバに参加させます。",
  "watchable": "プレイヤがサーバに参加するか期待します。",
  "requireable": "プレイヤがオンラインであることを要求します。",

  "arguments": {
    "message": {
      "type": "string",
      "description": "プレイヤがサーバーに参加したときに表示するメッセージです。"
    }
  },
  "outputs": {
    "message": {
        "type": "string",
        "description": "プレイヤがサーバーに参加したときに表示するメッセージです。"
    }
  }
}

=== TeamKun/Scenamatica/src/schema/schema/actions/entity/spawn.json
{
  "name": "entity_spawn",
  "description": "エンティティをスポーンさせます。",
  "base": "entity_$base",
  "events": [
    "org.bukkit.event.entity.EntitySpawnEvent"
  ],

  "executable": "エンティティをスポーンさせます。",
  "watchable": "エンティティがすぽーんすることを期待します。",
  "requireable": false,

  "arguments": {
    "entity": {
      "type": "entity",
      "requiredOn": ["execute"]
    }
  },
  "outputs": {
    "entity": {
      "type": "entity"
    }
  }
}
