=== TeamKun/Scenamatica/action.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "title": "Scenamatica Action",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the action"
    },
    "description": {
      "type": "string",
      "description": "A description of the action"
    },
    "base": {
      "type": "string",
      "description": "The base action to use for the action"
    },
    "executable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is executed"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is executable"
        }
      ]
    },
    "watchable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is watched"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is watchable"
        }
      ]
    },
    "requireable": {
      "oneOf": [
        {
          "type": "string",
          "description": "What will happen when the action is required"
        },
        {
          "type": "boolean",
          "const": false,
          "description": "Whether the action is requireable"
        }
      ]
    },
    "events": {
      "type": "array",
      "description": "The events that the action can emit",
      "items": {
        "type": "string"
      }
    },
    "arguments": {
      "type": "object",
      "description": "The arguments for the action",
      "additionalProperties": true,
      "patternProperties": {
        "^[a-zA-Z0-9_]+$": {
          "type": "object",
          "properties": {
            "requiredOn": {
              "oneOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "array",
                  "items": [
                    {
                      "type": "string",
                      "enum": [
                        "execute",
                        "watch",
                        "require"
                      ]
                    }
                  ]
                }
              ]
            },
            "availableFor": {
              "type": "array",
              "items": [
                {
                  "type": "string",
                  "enum": [
                    "execute",
                    "watch",
                    "require"
                  ]
                }
              ]
            }
          },
          "additionalProperties": true
        }
      }
    },
    "outputs": {
      "type": "object",
      "description": "The output of the action",
      "additionalProperties": true,
      "patternProperties": {
        "^[a-zA-Z0-9_]+$": {
          "type": "object",
          "properties": {
            "availableFor": {
              "type": "array",
              "items": [
                {
                  "type": "string",
                  "enum": [
                    "execute",
                    "watch",
                    "require"
                  ]
                }
              ]
            }
          },
          "additionalProperties": true
        }
      }
    }
  },
  "required": [
    "name",
    "description",
    "executable",
    "watchable",
    "requireable"
  ],
  "additionalProperties": false
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/level-change.json
{
  "name": "player_level_change",
  "description": "プレイヤの経験レベルを変更します。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerLevelChangeEvent"
  ],

  "executable": "プレイヤの経験レベルを変更します。",
  "watchable": "プレイヤの経験レベルが変更されることを期待します。",
  "requireable": "プレイヤの経験レベルが指定した値であることを要求します。",

  "arguments": {
    "oldLevel": {
      "type": "number",
      "description": "変更前の経験レベルです。",
      "availableFor": ["watch"]
    },
    "level": {
      "type": "number",
      "description": "変更後の経験レベルです。",
      "requiredOn": ["execute", "require"]
    }
  },
  "outputs": {
    "level": {
      "type": "number",
      "description": "変更後の経験レベルです。"
    },
    "oldLevel": {
      "type": "number",
      "description": "変更前の経験レベルです。"
    }
  }
}

=== TeamKun/Scenamatica/src/schema/schema/actions/player/advancement.json
{
  "name": "player_advancement",
  "description": "プレイヤに進捗を達成させます。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerAdvancementDoneEvent",
    "org.bukkit.event.player.PlayerAdvancementCriterionGrantEvent"
  ],

  "executable": "プレイヤに進捗を達成させるか、または達成度を変更します。",
  "watchable": "プレイヤの進捗が達成されるか、または達成度が変更されるか期待します。",
  "requireable": "プレイヤが進捗または達成度を満たしていることを要求します。",

  "arguments": {
    "player": {
      "type": "playerSpecifier",
      "description": "進捗を達成させるプレイヤです。",
      "requiredOn": ["execute", "require"]
    },
    "advancement": {
      "type": "namespacedKey",
      "description": "達成する進捗です。",
      "requiredOn": ["execute", "require"]
    },
    "criterion": {
      "type": "namespacedKey",
      "description": "達成する条件です。省略した場合は全ての条件を達成します。"
    }
  },
  "outputs": {
    "advancement": {
      "type": "namespacedKey",
      "description": "達成した進捗です。"
    },
    "criterion": {
      "type": "namespacedKey",
      "description": "達成した条件です。"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/death.json
{
  "name": "player_death",
  "description": "プレイヤをキルします。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.entity.PlayerDeathEvent"
  ],

  "executable": "プレイヤを死亡させます。",
  "watchable": "プレイヤが死亡するか期待します。",
  "requireable": "プレイヤが死亡していることを要求します。",

  "arguments": {
    "killer": {
      "type": "entitySpecifier",
      "description": "ターゲットを殺すプレイヤです。"
    },
    "deathMessage": {
      "type": "string",
      "description": "死亡メッセージです。",
      "availableFor": ["execute", "watch"]
    },
    "exp": {
      "type": "integer",
      "description": "死亡するプレイヤの新しい経験値です。",
      "minimum": 0,
      "availableFor": ["execute", "watch"]
    },
    "level": {
      "type": "integer",
      "description": "死亡するプレイヤの新しいレベルです。",
      "minimum": 0,
      "availableFor": ["execute", "watch"]
    },
    "totalExp": {
      "type": "integer",
      "description": "死亡するプレイヤの新しい総経験値です。",
      "minimum": 0,
      "availableFor": ["execute", "watch"]
    },
    "keepLevel": {
      "type": "boolean",
      "description": "死亡するプレイヤのレベルを保持するかどうかです。",
      "availableFor": ["execute", "watch"]
    },
    "keepInventory": {
      "type": "boolean",
      "description": "死亡するプレイヤのインベントリを保持するかどうかです。",
      "availableFor": ["execute", "watch"]
    },
    "doExpDrop": {
      "type": "boolean",
      "description": "死亡するプレイヤの経験値ドロップをするかどうかです。",
      "availableFor": ["execute", "watch"]
    }
  },
  "outputs": {
    "killer": {
      "type": "entitySpecifier",
      "description": "ターゲットを殺したプレイヤです。"
    },
    "deathMessage": {
      "type": "string",
      "description": "死亡メッセージです。"
    },
    "exp": {
      "type": "integer",
      "description": "死亡したプレイヤの新しい経験値です。",
      "minimum": 0,
      "availableFor": ["watch"]
    },
    "level": {
      "type": "integer",
      "description": "死亡したプレイヤの新しいレベルです。",
      "minimum": 0,
      "availableFor": ["watch"]
    },
    "totalExp": {
      "type": "integer",
      "description": "死亡したプレイヤの新しい総経験値です。",
      "minimum": 0,
      "availableFor": ["watch"]
    },
    "keepLevel": {
      "type": "boolean",
      "description": "死亡したプレイヤのレベルを保持するかどうかです。",
      "availableFor": ["watch"]
    },
    "keepInventory": {
      "type": "boolean",
      "description": "死亡したプレイヤのインベントリを保持するかどうかです。",
      "availableFor": ["watch"]
    },
    "doExpDrop": {
      "type": "boolean",
      "description": "死亡したプレイヤの経験値ドロップをするかどうかです。",
      "availableFor": ["watch"]
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/flight.json
{
  "name": "player_flight",
  "description": "プレイヤを飛行させます。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerToggleFlightEvent"
  ],

  "executable": "プレイヤの飛行状態を変更します。",
  "watchable": "プレイヤが飛行することを期待します。",
  "requireable": "プレイヤが飛行していることを要求します。",

  "arguments": {
    "flying": {
      "type": "boolean",
      "description": "プレイヤが飛行中かどうかです。",
      "requiredOn": ["execute", "require"]
    }
  }
}

=== TeamKun/Scenamatica/docs/schema/actions/server/plugin-enable.json
{
  "name": "server_plugin_enable",
  "description": "サーバのプラグインを有効化します。",
  "events": [
    "org.bukkit.event.server.PluginEnableEvent"
  ],

  "executable": "サーバのプラグインを有効化します。",
  "watchable": "サーバのプラグインが有効化されるか期待します。",
  "requireable": "プラグインが有効であることを要求します。",

  "arguments": {
    "plugin": {
      "type": "string",
      "description": "有効化されるプラグインです。",
      "requiredOn": ["execute", "require"]
    }
  },
  "outputs": {
    "plugin": {
      "type": "string",
      "description": "有効化されたプラグインです。"
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/item-break.json
{
  "name": "player_item_break",
  "description": "プレイヤにアイテムを破壊させます。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerItemBreakEvent"
  ],

  "executable": "プレイヤにアイテムを破壊させます。",
  "watchable": "プレイヤがアイテムを破壊するか期待します。",
  "requireable": false,

  "arguments": {
    "item": {
      "type": "itemStack",
      "description": "壊れたアイテムです。"
    },
    "slot": {
      "type": "itemSlot",
      "description": "壊れたアイテムが入っていたスロットです。"
    }
  },
  "outputs": {
    "item": {
      "type": "itemStack",
      "description": "壊れたアイテムです。"
    },
    "slot": {
      "type": "itemSlot",
      "description": "壊れたアイテムが入っていたスロットです。",
      "availableFor": ["execute"]
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/player/quit.json
{
  "name": "player_quit",
  "description": "プレイヤをサーバから退出させます。",
  "base": "player_$base",
  "events": [
    "org.bukkit.event.player.PlayerQuitEvent"
  ],

  "executable": "プレイヤをサーバから退出させます。",
  "watchable": "プレイヤがサーバから退出するか期待します。",
  "requireable": "プレイヤがオフラインであることを要求します。",


  "arguments": {
    "message": {
      "type": "string",
      "description": "プレイヤがサーバーから退出したときに表示するメッセージです。"
    },
    "reason": {
      "type": "string",
      "description": "プレイヤがサーバーから退出した原因です。",
      "enum": [
        "DISCONNECTED",
        "KICKED",
        "TIMED_OUT",
        "ERRONEOUS_STATE"
      ]
    }
  },
  "outputs": {
    "message": {
      "type": "string",
      "description": "プレイヤがサーバーから退出したときに表示されたメッセージです。"
    },
    "reason": {
      "type": "string",
      "description": "プレイヤがサーバーから退出した原因です。",
      "enum": [
        "DISCONNECTED",
        "KICKED",
        "TIMED_OUT",
        "ERRONEOUS_STATE"
      ]
    }
  }
}

=== TeamKun/Scenamatica/docs/src/schema/schema/actions/world/border.json
{
  "name": "world_border",
  "description": "ワールドのボーダを変更します。",
  "base": "world_$base",
  "events": [
    "org.bukkit.event.world.WorldBorderBoundsChangeEvent",
    "org.bukkit.event.world.WorldBorderCenterChangeEvent"
  ],

  "executable": "ワールドボーダを変更します。",
  "watchable": "ワールドボーダが変更されるか期待します。",
  "requireable": "ワールドボーダが指定されたものであることを要求します。",

  "arguments": {
    "type": {
      "type": "string",
      "description": "ワールドボーダの変更の種類です。",
      "enum": [
        "STARTED_MOVE",
        "INSTANT_MOVE"
      ],
      "availableFor": ["require"]
    },
    "size": {
      "type": "number",
      "description": "ワールドボーダのサイズです。"
    },
    "sizeOld": {
      "type": "number",
      "description": "ワールドボーダのサイズの変更前の値です。"
    },
    "duration": {
      "type": "number",
      "description": "ワールドボーダの変更にかかる時間です。"
    },
    "center": {
      "description": "ワールドボーダの中心座標です。",
      "type": "location"
    },
    "centerOld": {
      "description": "ワールドボーダの中心座標の変更前の値です。",
      "type": "location"
    }
  },
  "outputs": {
    "type": {
      "type": "string",
      "description": "ワールドボーダの変更の種類です。",
      "enum": [
        "STARTED_MOVE",
        "INSTANT_MOVE"
      ]
    },
    "size": {
      "type": "number",
      "description": "ワールドボーダのサイズです。"
    },
    "sizeOld": {
      "type": "number",
      "description": "ワールドボーダのサイズの変更前の値です。"
    },
    "duration": {
      "type": "number",
      "description": "ワールドボーダの変更にかかる時間です。"
    },
    "center": {
      "description": "ワールドボーダの中心座標です。",
      "type": "location"
    },
    "centerOld": {
      "description": "ワールドボーダの中心座標の変更前の値です。",
      "type": "location"
    }
  }
}
